apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-1-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: / 
    # No need to add canary weights as the other file specifies them


spec:
  rules:
  - http:
      paths:
      - path: /app # What will be called upon
        pathType: Prefix
        backend:
          service:
            name: app-1 # What it will be rerouted towards 
            port:
              number: 8080 # Will run on port 8080
