apiVersion: v1
kind: Service
metadata:
  name: app-1
  labels:
    run: app-1-sui
spec:
  selector:
    app: app-1
    run: app-1-sui
  ports:
  - protocol: TCP
    port: 8080 # The port that is exposed
    targetPort: 3000 # What is being used 
    
